CREATE TABLE QMAN_RUN_LOGS (
    ID         NUMBER       NOT NULL,
    RUN_ID     NUMBER       NOT NULL,
    QUEUE_ID   NUMBER       NOT NULL,
    GROUP_ID   NUMBER,
    TASK_ID    NUMBER,
    QUEUE_CODE VARCHAR2(50) NOT NULL,
    GROUP_CODE VARCHAR2(50),
    TASK_CODE  VARCHAR2(50),
    RUN_PROC   VARCHAR2(100),
    BYPASS     NUMBER(1, 0),
    START_DATE DATE         NOT NULL,
    END_DATE   DATE,
    STATE      VARCHAR2(15) NOT NULL,
    SESSIONID  NUMBER,
    SID        NUMBER,

    CONSTRAINT QMAN_RUN_LOGS_PK PRIMARY KEY (ID)
);

COMMENT ON TABLE QMAN_RUN_LOGS IS 'Журнал выполнения очередей и заданий';
