CREATE TABLE QMAN_DEPENDS (
    ID        NUMBER NOT NULL,
    QUEUE_ID  NUMBER NOT NULL,
    GROUP_ID  NUMBER NOT NULL,
    PARENT_ID NUMBER NOT NULL,
    CHILD_ID  NUMBER NOT NULL,

    CONSTRAINT QMAN_DEPENDS_PK PRIMARY KEY (ID),
    CONSTRAINT QMAN_DEPENDS_FK01 FOREIGN KEY (QUEUE_ID) REFERENCES QMAN_QUEUES (ID),
    CONSTRAINT QMAN_DEPENDS_FK02 FOREIGN KEY (GROUP_ID) REFERENCES QMAN_GROUPS (ID),
    CONSTRAINT QMAN_DEPENDS_FK03 FOREIGN KEY (PARENT_ID) REFERENCES QMAN_TASKS (ID),
    CONSTRAINT QMAN_DEPENDS_FK04 FOREIGN KEY (CHILD_ID) REFERENCES QMAN_TASKS (ID),
    CONSTRAINT QMAN_DEPENDS_UK01 UNIQUE (PARENT_ID, CHILD_ID)
);

COMMENT ON TABLE QMAN_DEPENDS IS 'Зависимости заданий';
