CREATE TABLE QMAN_QUEUES (
    ID         NUMBER        NOT NULL,
    CODE       VARCHAR2(50)  NOT NULL,
    NAME       VARCHAR2(100) NOT NULL,
    ENABLED    NUMBER(1, 0),
    ASYNC      NUMBER(1, 0),
    STATE      VARCHAR2(15)  DEFAULT 'OK' NOT NULL,
    RUN_ID     NUMBER,
    RUN_LIMIT  NUMBER,
    RUN_HOURS  VARCHAR2(100),
    RUN_NEXT   DATE,
    CHECK_PROC VARCHAR2(100),
    NOTIFY     NUMBER,

    CHECK (enabled IN (0, 1)),
    CHECK (async IN (0, 1)),

    CONSTRAINT QMAN_QUEUES_PK PRIMARY KEY (ID),
    CONSTRAINT QMAN_QUEUES_UK01 UNIQUE (CODE)
);

COMMENT ON TABLE QMAN_QUEUES IS 'Очереди заданий';
