CREATE TABLE QMAN_TASKS (
    ID        NUMBER        NOT NULL,
    QUEUE_ID  NUMBER        NOT NULL,
    GROUP_ID  NUMBER        NOT NULL,
    ORDER_NUM NUMBER        NOT NULL,
    CODE      VARCHAR2(50)  NOT NULL,
    RUN_PROC  VARCHAR2(100) NOT NULL,
    ENABLED   NUMBER(1, 0),
    BYPASS    NUMBER(1, 0),
    ASYNC     NUMBER(1, 0),
    STATE     VARCHAR2(15)  DEFAULT 'OK' NOT NULL,
    RUN_ID    NUMBER,
    SESSIONID NUMBER,
    SID       NUMBER,

    CHECK (order_num = trunc(order_num)),
    CHECK (enabled IN (0, 1)),
    CHECK (bypass IN (0, 1, 2)),
    CHECK (async IN (0, 1)),

    CONSTRAINT QMAN_TASKS_PK PRIMARY KEY (ID),
    CONSTRAINT QMAN_TASKS_FK01 FOREIGN KEY (QUEUE_ID) REFERENCES QMAN_QUEUES (ID),
    CONSTRAINT QMAN_TASKS_FK02 FOREIGN KEY (GROUP_ID) REFERENCES QMAN_GROUPS (ID),
    CONSTRAINT QMAN_TASKS_UK01 UNIQUE (QUEUE_ID, CODE),
    CONSTRAINT QMAN_TASKS_UK02 UNIQUE (QUEUE_ID, ORDER_NUM)
);

COMMENT ON TABLE QMAN_TASKS IS 'Задания';
